# Generated by Django 2.1.3 on 2018-12-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bugzilla_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directs', to='org.Person')),
            ],
        ),
    ]
